name: CI Pipeline

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  
jobs: 
  build-test: 
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2

      - name: Install dependencies 
        run: npm install
